import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');
const BASE_WIDTH = 390;
const BASE_HEIGHT = 844;
function normalize(size, based = 'width') {
  const scale = based === 'height' ? SCREEN_HEIGHT / BASE_HEIGHT : SCREEN_WIDTH / BASE_WIDTH;
  return Math.round(size * scale);
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#Fafafa' },
  screen: { flex: 1, backgroundColor: '#FAFAFA' },
  loadingText: { marginTop: normalize(100, 'height'), textAlign: 'center', fontSize: normalize(16) },
 headerLine: {
    height: 1,
    backgroundColor: '#B5B5B5',
    marginTop: normalize(-1),
  },
  headerTitle: { fontSize: normalize(18), alignItems: 'center', color: '#000' , marginTop: normalize(-8),},
  tripInfo: { backgroundColor: '#FAFAFA', padding: normalize(16), paddingBottom: normalize(4) },
  tripInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  tripTitle: { fontSize: normalize(20), color: '#1E1E1E' },
  totalBudgetLabel: { fontSize: normalize(14), color: '#1E1E1E', top: -2 },
  budget: { color: '#4F46E5', fontSize: normalize(14), marginTop: normalize(4) },
  budgetUnit: { color: '#4F46E5', fontSize: normalize(14) },
  dateText: { fontSize: normalize(14), color: '#7E7E7E', marginTop: normalize(4), marginBottom: 0 },
  tabScrollWrapper: {
    backgroundColor: '#FAFAFA',
    borderBottomWidth: 1,
    borderColor: '#E5E7EB',
  },
  tabContainer: { flexDirection: 'row', paddingHorizontal: normalize(6), paddingVertical: normalize(6) },
  tabBox: { alignItems: 'center', marginHorizontal: normalize(6), paddingHorizontal: normalize(10) },
  tabText: { fontSize: normalize(18), color: '#9CA3AF' },
  tabTextSelected: { color: '#4F46E5', fontWeight: 'bold' },
  activeBar: {
    marginTop: normalize(5),
    height: normalize(4),
    width: normalize(80),
    backgroundColor: '#4F46E5',
    borderRadius: 2,
  },
  container: {
    paddingHorizontal: normalize(16),
    marginBottom: -normalize(70),
    marginTop: normalize(20),
    backgroundColor: '#FAFAFA',
  },
  bottomButtonContainer1: {
    flexDirection: 'row',
    backgroundColor: '#fafafa',
    paddingVertical: normalize(20),
    paddingHorizontal: normalize(16),
    borderRadius: normalize(12),
    marginBottom: -normalize(20)
  },
bottomButtonContainer: {
  flexDirection: 'row',
  backgroundColor: '#fafafa',
  paddingVertical: normalize(18),
  paddingHorizontal: normalize(20),
  top:normalize(10),
  borderRadius: normalize(12),
  paddingBottom: normalize(20), // 👈 이거 추가
},
  placeRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: normalize(32),
  },
  timeline: {
    width: normalize(30),
    alignItems: 'center',
    position: 'relative',
  },
  dot: {
    width: normalize(20),
    height: normalize(20),
    borderRadius: normalize(10),
    backgroundColor: '#6366F1',
    position: 'absolute',
    top: normalize(40),
    zIndex: 2,
  },
  verticalLine: {
    position: 'absolute',
    top: -normalize(20),
    left: normalize(13),
    width: normalize(4),
    height: normalize(330, 'height'),
    backgroundColor: '#A19CFF',
  },
  placeContent: { flex: 1, marginLeft: normalize(10) },
  placeCard: {
    backgroundColor: '#fff',
    padding: normalize(16),
    paddingBottom: normalize(10),
    borderRadius: normalize(20),
    marginBottom: -normalize(25),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  placeCard2: {
    backgroundColor: '#fff',
    padding: normalize(16),
    paddingRight: normalize(5),
    paddingLeft: normalize(12),
    paddingBottom: normalize(6),
    borderRadius: normalize(20),
    marginBottom: -normalize(35),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    width: '85%',
    left: -normalize(20),
  },
  placeCard3: {
    backgroundColor: '#fff',
    padding: normalize(16),
    paddingRight: normalize(5),
    paddingLeft: normalize(16),
    paddingBottom: normalize(6),
    borderRadius: normalize(20),
    marginBottom: -normalize(40),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    width: '88%',
    left: -normalize(20),
  },
  placeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  placeName: { fontSize: normalize(16), marginBottom: normalize(4), color: '#373737' },
  placeCost: {
    fontSize: normalize(15),
    fontWeight: '600',
    fontStyle: 'Inter',
    color: '#8B76E8',
    bottom: -normalize(15),
  },
  placeType: { fontSize: normalize(13), color: '#9CA3AF', marginBottom: normalize(4) , top:normalize(2)},
  keywords: { fontSize: normalize(12), color: '#333333', marginBottom: normalize(6) },
  transportRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: normalize(12),
    marginBottom: normalize(12),
  },
  placeNameInput: {
    fontSize: normalize(18),
    marginBottom: normalize(19),
    color: '#373737',
    paddingVertical: normalize(4),
    paddingTop: normalize(18),
  },
  transportItem: {
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: normalize(120),
    marginLeft: normalize(10),
    justifyContent: 'center',
  },
  transportText: {
    marginLeft: normalize(6),
    fontSize: normalize(14),
    color: '#000',
  },
  transportTexts: {
    marginLeft: normalize(-28),
    fontSize: normalize(14),
    color: '#000',
  },
  transportTextss: {
    marginLeft: normalize(14),
    fontSize: normalize(14),
    color: '#000',
  },
  dragHandle: {
    position: 'absolute',
    left: -normalize(45),
    top: normalize(25),
    padding: normalize(4),
    zIndex: 5,
  },
  editButton: {
    flex: 1,
    height: normalize(45),
    borderRadius: normalize(12),
    borderWidth: 1,
    borderColor: '#4F46E5',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  editButtonText: {
    fontSize: normalize(16),
    color: '#4F46E5',
  },
  saveButton: {
    flex: 1,
    height: normalize(45),
    borderRadius: normalize(12),
    borderWidth: 1,
    borderColor: '#4F46E5',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonText: {
    textAlign: 'center',
    color: '#4F46E5',
    fontSize: normalize(16),
  },
  regenerateButtonWrapper: {
    position: 'absolute',
    bottom: normalize(50),
    left: normalize(16),
    right: normalize(16),
    backgroundColor: '#fafafa',
    paddingVertical: normalize(5),
    borderRadius: normalize(12),
  },
  regenerateButton: {
    backgroundColor: '#4F46E5',
    borderRadius: normalize(10),
    paddingVertical: normalize(12),
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#4F46E5',
  },
  regenerateButtonText: {
    color: '#fff',
    fontSize: normalize(16),
  },
  fixedDoneButtonWrapper: {
    position: 'absolute',
    bottom: normalize(5),
    left: normalize(20),
    right: normalize(20),
    backgroundColor: '#4F46E5',
    borderRadius: normalize(12),
    paddingVertical: normalize(14),
    alignItems: 'center',
  },
  fixedDoneButton: {
    width: '100%',
    alignItems: 'center',
  },
  fixedDoneButtonText: {
    color: '#fff',
    fontSize: normalize(18),
  },
});
